services:
  postgres:
    image: postgres:16-alpine
    container_name: fisoft_postgres
    restart: always
    environment:
      POSTGRES_DB: fisoft_db
      POSTGRES_USER: fisoft_user
      POSTGRES_PASSWORD: fisoft_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fisoft_user -d fisoft_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-03-21T23-13-43Z
    container_name: fisoft_minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpassword
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fisoft_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: "jdbc:postgresql://postgres:5432/fisoft_db"
      DB_USER: "fisoft_user"
      DB_PASSWORD: "fisoft_password"
      MINIO_URL: "http://minio:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadminpassword"
      MINIO_BUCKET_NAME: "fiperde-media"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data:
