ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.ilyasdemirkiran.MainKt.module
      - com.ilyasdemirkiran.HttpKt.configureHttp
      - com.ilyasdemirkiran.SerializationKt.configureSerialization
      - com.ilyasdemirkiran.RoutingKt.configureRouting

supabase:
  url: ${SUPABASE_URL}
  serviceRoleKey: ${SUPABASE_SERVICE_ROLE_KEY}

db:
  url: ${DB_URL}
  user: ${DB_USER}
  password: ${DB_PASSWORD}